import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Web3ReactProvider } from "@web3-react/core";
import { Web3Provider } from "@ethersproject/providers";
import ConnectWallet from "../components/ConnectWallet";

function getLibrary(provider) {
  return new Web3Provider(provider);
}
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Web3ReactProvider getLibrary={getLibrary}>
        <ConnectWallet />
      </Web3ReactProvider>
      <main></main>
    </div>
  );
}
